"use client";

import { memo, useEffect, useRef, useId } from "react";
import type { DiagramData, ThemeConfig } from "@/types/presentation";

// Lazy-load mermaid to avoid ~800KB in the initial bundle
let mermaidPromise: Promise<typeof import("mermaid")> | null = null;
function getMermaid() {
  if (!mermaidPromise) {
    mermaidPromise = import("mermaid").then((m) => {
      m.default.initialize({ startOnLoad: false, theme: "default" });
      return m;
    });
  }
  return mermaidPromise;
}

// ---------------------------------------------------------------------------
// Mermaid render queue — serializes all renders to prevent race conditions.
// Mermaid.js uses internal DOM state that corrupts when multiple render() calls
// run concurrently, producing empty <g></g> SVGs.
// ---------------------------------------------------------------------------
let renderQueue: Promise<void> = Promise.resolve();

function queueMermaidRender(
  id: string,
  syntax: string,
): Promise<string> {
  return new Promise((resolve, reject) => {
    renderQueue = renderQueue.then(async () => {
      try {
        const m = await getMermaid();
        // Clean up any leftover temp element from a prior render with this id
        document.querySelector(`#d${id}`)?.remove();
        const { svg } = await m.default.render(id, syntax);
        resolve(svg);
      } catch (err) {
        reject(err);
      }
    });
  });
}

function isSvgEmpty(svg: string): boolean {
  // Mermaid produces <style>...</style><g></g> when render fails silently
  return !svg.includes("<path") && !svg.includes("<rect") && !svg.includes("<text") && !svg.includes("<polygon");
}

function fixSvgScaling(container: HTMLDivElement) {
  const svgEl = container.querySelector("svg");
  if (!svgEl) return;
  if (!svgEl.getAttribute("viewBox")) {
    // Mermaid sometimes omits viewBox, causing 300x150 default size
    const bbox = svgEl.getBBox();
    if (bbox.width > 0 && bbox.height > 0) {
      const pad = 8;
      svgEl.setAttribute(
        "viewBox",
        `${bbox.x - pad} ${bbox.y - pad} ${bbox.width + pad * 2} ${bbox.height + pad * 2}`,
      );
    }
  }
  svgEl.setAttribute("width", "100%");
  svgEl.removeAttribute("height");
  svgEl.style.maxHeight = "100%";
}

/** Add <title> elements to Mermaid SVG nodes for native browser tooltips */
function addMermaidTooltips(container: HTMLDivElement) {
  const svgEl = container.querySelector("svg");
  if (!svgEl) return;

  // Mermaid wraps each node in a <g> with class "node" or "actor" etc.
  const nodes = svgEl.querySelectorAll("g.node, g.actor, g.task, g.section");
  for (const node of nodes) {
    // Skip if already has a <title>
    if (node.querySelector(":scope > title")) continue;

    // Extract text from the node's <text> or <foreignObject> elements
    const textEl = node.querySelector("text, foreignObject");
    const text = textEl?.textContent?.trim();
    if (text) {
      const titleEl = document.createElementNS("http://www.w3.org/2000/svg", "title");
      titleEl.textContent = text;
      node.prepend(titleEl);
    }
  }
}

interface DiagramBlockProps {
  data: DiagramData;
  theme: ThemeConfig;
}

export const DiagramBlock = memo(function DiagramBlock({ data, theme }: DiagramBlockProps) {
  const ref = useRef<HTMLDivElement>(null);
  const uid = useId().replace(/:/g, "_");

  useEffect(() => {
    if (!ref.current || !data.syntax) return;
    let cancelled = false;

    async function renderWithRetry(id: string, attempt: number) {
      try {
        const svg = await queueMermaidRender(id, data.syntax);
        if (cancelled || !ref.current) return;

        if (isSvgEmpty(svg) && attempt < 3) {
          // Empty render — retry after a short delay
          const retryId = `${id}_r${attempt + 1}`;
          setTimeout(() => renderWithRetry(retryId, attempt + 1), 150 * (attempt + 1));
          return;
        }

        // Mermaid SVG output is trusted (generated by the library, not user HTML)
        ref.current.replaceChildren();
        ref.current.insertAdjacentHTML("afterbegin", svg);
        fixSvgScaling(ref.current);
        addMermaidTooltips(ref.current);
      } catch {
        if (!cancelled && ref.current) {
          const errDiv = document.createElement("div");
          errDiv.style.cssText = "color: #EF4444; font-size: 0.7em;";
          errDiv.textContent = "Diagram syntax error";
          ref.current.replaceChildren(errDiv);
        }
      }
    }

    renderWithRetry(`mermaid_${uid}`, 0);
    return () => { cancelled = true; };
  }, [data.syntax, uid]);

  return (
    <div className="flex flex-col items-center gap-[0.2em] w-full">
      <div
        ref={ref}
        className="w-full flex items-center justify-center [&_svg]:max-w-full [&_svg]:max-h-full"
      />
      {data.caption && (
        <div className="text-[0.55em] opacity-60 italic" style={{ color: theme.textColor }}>
          {data.caption}
        </div>
      )}
    </div>
  );
});
