"use client";

import type { ThemeConfig, IllustrationData } from "@/types/presentation";

interface IllustrationBlockProps {
  data: IllustrationData;
  theme: ThemeConfig;
}

/**
 * Renders inline SVG illustrations from FINNISH integration
 * Handles SVG content, Mermaid diagrams, and placeholder states
 *
 * SECURITY NOTE: dangerouslySetInnerHTML is used for SVG rendering.
 * Content is generated by internal AI services, not direct user input.
 * All SVG content should be sanitized before being stored in the database.
 */
export function IllustrationBlock({ data, theme }: IllustrationBlockProps) {
  // If we have SVG content, render it
  if (data.svgContent && data.svgContent.trim().startsWith("<svg")) {
    return (
      <figure className="flex flex-col items-center gap-[0.3em]">
        <div
          className="rounded-[0.3em] overflow-hidden"
          style={{ maxWidth: "100%", maxHeight: "100%" }}
          dangerouslySetInnerHTML={{ __html: data.svgContent }}
        />
        {(data.caption || data.sourcePrompt) && (
          <figcaption
            className="text-[0.55em] opacity-60 italic text-center"
            style={{ color: theme.textColor }}
          >
            {data.caption || data.sourcePrompt}
          </figcaption>
        )}
      </figure>
    );
  }

  // If it looks like Mermaid syntax, we'd dynamically import mermaid here
  // For now, show a placeholder
  if (data.svgContent && (data.svgContent.includes("graph") || data.svgContent.includes("flowchart"))) {
    return (
      <div
        className="flex flex-col items-center justify-center rounded-[0.3em] p-[1em] h-full"
        style={{ backgroundColor: `${theme.primaryColor}08` }}
      >
        <div className="text-[0.7em] opacity-50 text-center">
          Mermaid Diagram
          {data.sourcePrompt && <div className="text-[0.6em] mt-1">{data.sourcePrompt}</div>}
        </div>
      </div>
    );
  }

  // Placeholder when no content yet
  return (
    <div
      className="flex flex-col items-center justify-center rounded-[0.3em] p-[1em] h-full"
      style={{ backgroundColor: `${theme.primaryColor}08` }}
    >
      <div className="text-[0.7em] opacity-50 text-center">
        {data.sourcePrompt || data.alt || "Illustration placeholder"}
        {data.domain && <div className="text-[0.6em] mt-1">{data.domain}</div>}
      </div>
    </div>
  );
}
