steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/metal-node-486118-t7/scholarsync/web:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/metal-node-486118-t7/scholarsync/web:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'scholarsync-web'
      - '--image'
      - 'asia-south1-docker.pkg.dev/metal-node-486118-t7/scholarsync/web:$COMMIT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GCS_BUCKET_NAME=scholarsync-pdfs,GCS_PROJECT_ID=metal-node-486118-t7'

images:
  - 'asia-south1-docker.pkg.dev/metal-node-486118-t7/scholarsync/web:$COMMIT_SHA'
