/**
 * Publication Polish Post-Processor
 *
 * Applies publication-quality styling to SVG diagrams generated by any backend.
 * Normalizes fonts, stroke widths, viewBox, and removes redundant elements.
 */

import type { JournalPreset } from './journal-presets';

// =============================================================================
// TYPES
// =============================================================================

export interface PublicationPolishOptions {
  /** Font family for sans-serif text (default: Arial, Helvetica, sans-serif) */
  sansFont?: string;
  /** Font family for serif text (default: Times New Roman, Times, Georgia, serif) */
  serifFont?: string;
  /** Minimum font size in pt (default: 8) */
  minFontSize?: number;
  /** Minimum stroke width in pt (default: 0.5) */
  minStrokeWidth?: number;
  /** Whether to add anti-aliasing hints (default: true) */
  antiAlias?: boolean;
  /** Optional journal preset to apply */
  journalPreset?: JournalPreset;
  /** Optional custom color palette to apply */
  colorPalette?: string[];
}

const DEFAULT_OPTIONS: Required<Omit<PublicationPolishOptions, 'journalPreset' | 'colorPalette'>> = {
  sansFont: 'Arial, Helvetica, sans-serif',
  serifFont: '"Times New Roman", Times, Georgia, serif',
  minFontSize: 8,
  minStrokeWidth: 0.5,
  antiAlias: true,
};

// =============================================================================
// PUBLICATION POLISH PROCESSOR
// =============================================================================

export class PublicationPolishProcessor {
  private options: Required<Omit<PublicationPolishOptions, 'journalPreset' | 'colorPalette'>> & {
    journalPreset?: JournalPreset;
    colorPalette?: string[];
  };

  constructor(options: PublicationPolishOptions = {}) {
    this.options = {
      ...DEFAULT_OPTIONS,
      ...options,
    };
  }

  /**
   * Apply all publication polish steps to an SVG string
   */
  polish(svg: string): string {
    if (!svg || svg.trim().length === 0) {
      return svg;
    }

    let result = svg;

    // Apply journal preset overrides if specified
    if (this.options.journalPreset) {
      this.applyPresetOverrides(this.options.journalPreset);
    }

    result = this.normalizeFonts(result);
    result = this.enforceMinFontSize(result);
    result = this.enforceMinStrokeWidth(result);
    result = this.ensureViewBox(result);
    result = this.removeEmptyGroups(result);
    result = this.removeRedundantElements(result);

    if (this.options.antiAlias) {
      result = this.addAntiAliasing(result);
    }

    if (this.options.journalPreset?.maxWidthMm) {
      result = this.constrainWidth(result, this.options.journalPreset.maxWidthMm);
    }

    if (this.options.colorPalette && this.options.colorPalette.length > 0) {
      result = this.applyColorPalette(result, this.options.colorPalette);
    }

    return result;
  }

  /**
   * Apply preset overrides to current options
   */
  private applyPresetOverrides(preset: JournalPreset): void {
    if (preset.fontFamily) {
      this.options.sansFont = preset.fontFamily;
    }
    if (preset.minFontSizePt) {
      this.options.minFontSize = preset.minFontSizePt;
    }
  }

  /**
   * Normalize font families to publication standards
   */
  normalizeFonts(svg: string): string {
    const sansFont = this.options.sansFont;

    // Replace common non-publication fonts in font-family attributes
    let result = svg.replace(
      /font-family\s*=\s*"([^"]*)"/g,
      (_match, fontValue: string) => {
        const normalized = this.normalizeOneFont(fontValue, sansFont);
        return `font-family="${normalized}"`;
      }
    );

    // Also handle font-family in style attributes
    result = result.replace(
      /font-family\s*:\s*([^;"]+)/g,
      (_match, fontValue: string) => {
        const normalized = this.normalizeOneFont(fontValue.trim(), sansFont);
        return `font-family: ${normalized}`;
      }
    );

    return result;
  }

  private normalizeOneFont(fontValue: string, sansFont: string): string {
    const lower = fontValue.toLowerCase();
    // Keep serif fonts as-is if they're already publication-quality
    if (
      lower.includes('times') ||
      lower.includes('georgia') ||
      lower.includes('garamond')
    ) {
      return fontValue;
    }
    // Replace non-standard sans-serif fonts
    if (
      lower.includes('sans') ||
      lower.includes('verdana') ||
      lower.includes('tahoma') ||
      lower.includes('segoe') ||
      lower.includes('roboto') ||
      lower.includes('open sans') ||
      lower.includes('lato') ||
      lower.includes('system-ui') ||
      lower.includes('-apple-system') ||
      lower === 'inherit'
    ) {
      return sansFont;
    }
    // If it's Arial or Helvetica, keep it
    if (lower.includes('arial') || lower.includes('helvetica')) {
      return fontValue;
    }
    // Default: replace with sans font
    return sansFont;
  }

  /**
   * Ensure all text has at least the minimum font size
   */
  enforceMinFontSize(svg: string): string {
    const minSize = this.options.minFontSize;

    // Handle font-size attribute
    let result = svg.replace(
      /font-size\s*=\s*"(\d+\.?\d*)(pt|px|em|rem|%)?\s*"/g,
      (_match, size: string, unit: string) => {
        const numSize = parseFloat(size);
        const effectiveUnit = unit || 'px';

        let ptSize: number;
        if (effectiveUnit === 'pt') {
          ptSize = numSize;
        } else if (effectiveUnit === 'px') {
          ptSize = numSize * 0.75; // 1px = 0.75pt
        } else {
          // For em/rem/%, don't modify
          return _match;
        }

        if (ptSize < minSize) {
          const newSize = effectiveUnit === 'pt' ? minSize : minSize / 0.75;
          return `font-size="${newSize}${effectiveUnit}"`;
        }
        return _match;
      }
    );

    // Handle font-size in style attributes
    result = result.replace(
      /font-size\s*:\s*(\d+\.?\d*)(pt|px|em|rem|%)?/g,
      (_match, size: string, unit: string) => {
        const numSize = parseFloat(size);
        const effectiveUnit = unit || 'px';

        let ptSize: number;
        if (effectiveUnit === 'pt') {
          ptSize = numSize;
        } else if (effectiveUnit === 'px') {
          ptSize = numSize * 0.75;
        } else {
          return _match;
        }

        if (ptSize < minSize) {
          const newSize = effectiveUnit === 'pt' ? minSize : minSize / 0.75;
          return `font-size: ${newSize}${effectiveUnit}`;
        }
        return _match;
      }
    );

    return result;
  }

  /**
   * Ensure all strokes have at least the minimum width
   */
  enforceMinStrokeWidth(svg: string): string {
    const minWidth = this.options.minStrokeWidth;

    // Handle stroke-width attribute
    let result = svg.replace(
      /stroke-width\s*=\s*"(\d+\.?\d*)(pt|px)?"/g,
      (_match, width: string, unit: string) => {
        const numWidth = parseFloat(width);
        const effectiveUnit = unit || 'px';

        let ptWidth: number;
        if (effectiveUnit === 'pt') {
          ptWidth = numWidth;
        } else {
          ptWidth = numWidth * 0.75;
        }

        if (ptWidth < minWidth) {
          const newWidth = effectiveUnit === 'pt' ? minWidth : minWidth / 0.75;
          return `stroke-width="${newWidth}${effectiveUnit === 'pt' ? 'pt' : ''}"`;
        }
        return _match;
      }
    );

    // Handle stroke-width in style attributes
    result = result.replace(
      /stroke-width\s*:\s*(\d+\.?\d*)(pt|px)?/g,
      (_match, width: string, unit: string) => {
        const numWidth = parseFloat(width);
        const effectiveUnit = unit || 'px';

        let ptWidth: number;
        if (effectiveUnit === 'pt') {
          ptWidth = numWidth;
        } else {
          ptWidth = numWidth * 0.75;
        }

        if (ptWidth < minWidth) {
          const newWidth = effectiveUnit === 'pt' ? minWidth : minWidth / 0.75;
          return `stroke-width: ${newWidth}${effectiveUnit === 'pt' ? 'pt' : ''}`;
        }
        return _match;
      }
    );

    return result;
  }

  /**
   * Ensure SVG has a proper viewBox attribute
   */
  ensureViewBox(svg: string): string {
    // Check if viewBox already exists
    if (/viewBox\s*=\s*"[^"]*"/.test(svg)) {
      return svg;
    }

    // Try to extract width and height
    const widthMatch = svg.match(/<svg[^>]*\swidth\s*=\s*"(\d+\.?\d*)/);
    const heightMatch = svg.match(/<svg[^>]*\sheight\s*=\s*"(\d+\.?\d*)/);

    const width = widthMatch ? parseFloat(widthMatch[1]) : 800;
    const height = heightMatch ? parseFloat(heightMatch[1]) : 600;

    // Add viewBox to the svg tag
    return svg.replace(
      /<svg([^>]*)>/,
      `<svg$1 viewBox="0 0 ${width} ${height}">`
    );
  }

  /**
   * Remove empty <g> groups that contain no children
   */
  removeEmptyGroups(svg: string): string {
    // Iteratively remove empty groups (nested empties)
    let result = svg;
    let prev = '';
    let iterations = 0;
    const maxIterations = 10;

    while (result !== prev && iterations < maxIterations) {
      prev = result;
      // Match <g ...></g> or <g .../> with only whitespace inside
      result = result.replace(/<g([^>]*)>\s*<\/g>/g, '');
      // Also match self-closing empty groups
      result = result.replace(/<g([^>]*)\s*\/>/g, '');
      iterations++;
    }

    return result;
  }

  /**
   * Remove redundant elements (empty text, invisible elements)
   */
  removeRedundantElements(svg: string): string {
    let result = svg;

    // Remove empty text elements
    result = result.replace(/<text([^>]*)>\s*<\/text>/g, '');

    // Remove elements with display:none
    result = result.replace(/<[^>]*display\s*:\s*none[^>]*>[\s\S]*?<\/[^>]+>/g, '');
    result = result.replace(/<[^>]*display\s*=\s*"none"[^>]*>[\s\S]*?<\/[^>]+>/g, '');

    // Remove empty defs
    result = result.replace(/<defs>\s*<\/defs>/g, '');

    return result;
  }

  /**
   * Add anti-aliasing rendering hints
   */
  addAntiAliasing(svg: string): string {
    // Add shape-rendering and text-rendering if not present
    if (svg.includes('shape-rendering')) {
      return svg;
    }

    return svg.replace(
      /<svg([^>]*)>/,
      '<svg$1 shape-rendering="geometricPrecision" text-rendering="geometricPrecision">'
    );
  }

  /**
   * Constrain the SVG width to a journal-specified maximum (in mm)
   */
  constrainWidth(svg: string, maxWidthMm: number): string {
    // Convert mm to px (assuming 96 DPI: 1mm = 3.7795px)
    const maxWidthPx = maxWidthMm * 3.7795;

    // Extract current width from viewBox or width attribute
    const viewBoxMatch = svg.match(/viewBox\s*=\s*"(\d+\.?\d*)\s+(\d+\.?\d*)\s+(\d+\.?\d*)\s+(\d+\.?\d*)"/);

    if (viewBoxMatch) {
      const vbWidth = parseFloat(viewBoxMatch[3]);
      const vbHeight = parseFloat(viewBoxMatch[4]);

      if (vbWidth > maxWidthPx) {
        const scale = maxWidthPx / vbWidth;
        const newHeight = vbHeight * scale;

        // Update width/height attributes but keep viewBox
        let result = svg.replace(
          /(<svg[^>]*)\swidth\s*=\s*"[^"]*"/,
          `$1 width="${maxWidthMm}mm"`
        );
        result = result.replace(
          /(<svg[^>]*)\sheight\s*=\s*"[^"]*"/,
          `$1 height="${(newHeight / 3.7795).toFixed(1)}mm"`
        );

        // If no width attribute exists, add one
        if (!svg.includes('width=')) {
          result = result.replace(
            /<svg([^>]*)>/,
            `<svg$1 width="${maxWidthMm}mm">`
          );
        }

        return result;
      }
    }

    return svg;
  }

  /**
   * Apply a custom color palette to fill colors in the SVG
   */
  applyColorPalette(svg: string, palette: string[]): string {
    if (palette.length === 0) return svg;

    // Find all unique fill colors (excluding none, white, black, url())
    const fillColors = new Set<string>();
    const fillRegex = /fill\s*=\s*"(#[0-9a-fA-F]{3,8})"/g;
    let match;

    while ((match = fillRegex.exec(svg)) !== null) {
      const color = match[1].toLowerCase();
      if (color !== '#fff' && color !== '#ffffff' && color !== '#000' && color !== '#000000') {
        fillColors.add(match[1]);
      }
    }

    // Map old colors to new palette colors
    let result = svg;
    const colorArray = Array.from(fillColors);
    colorArray.forEach((oldColor, index) => {
      const newColor = palette[index % palette.length];
      result = result.split(`fill="${oldColor}"`).join(`fill="${newColor}"`);
    });

    return result;
  }
}

/**
 * Convenience function to polish an SVG with default options
 */
export function polishSvg(svg: string, options?: PublicationPolishOptions): string {
  const processor = new PublicationPolishProcessor(options);
  return processor.polish(svg);
}
