/**
 * TikZ/LaTeX Exporter
 * Exports Fabric.js canvas to TikZ code for LaTeX documents
 */

import type { Canvas as FabricCanvas, FabricObject } from 'fabric';
import type {
  Exporter,
  TikZExportOptions,
  ExportResult,
  ExportProgressCallback,
} from './types';
import { MIME_TYPES, FILE_EXTENSIONS } from './types';

/**
 * TikZ preamble packages required for the generated code
 */
const TIKZ_PACKAGES = [
  '\\usepackage{tikz}',
  '\\usepackage{xcolor}',
  '\\usetikzlibrary{shapes,arrows,positioning,calc,patterns,decorations.pathmorphing}',
];

/**
 * Unit conversion factors from pixels
 */
const UNIT_FACTORS: Record<string, number> = {
  cm: 0.0264583, // 1px = 0.0264583cm (assuming 96 DPI)
  mm: 0.264583,  // 1px = 0.264583mm
  pt: 0.75,      // 1px = 0.75pt
  in: 0.0104167, // 1px = 0.0104167in
};

/**
 * TikZ Exporter class
 * Handles export of Fabric.js canvas to TikZ/LaTeX format
 */
export class TikZExporter implements Exporter<TikZExportOptions> {
  readonly format = 'tikz' as const;

  private colorIndex = 0;
  private definedColors: Map<string, string> = new Map();

  /**
   * Get default export options
   */
  getDefaultOptions(): Omit<TikZExportOptions, 'format'> {
    return {
      standalone: true,
      includePreamble: true,
      scale: 1,
      unit: 'cm',
      includeComments: true,
      filename: 'illustration',
    };
  }

  /**
   * Validate export options
   */
  validateOptions(options?: Partial<TikZExportOptions>): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (options?.scale !== undefined && options.scale <= 0) {
      errors.push('Scale must be a positive number');
    }

    if (options?.unit && !['cm', 'mm', 'pt', 'in'].includes(options.unit)) {
      errors.push('Unit must be one of: cm, mm, pt, in');
    }

    return { valid: errors.length === 0, errors };
  }

  /**
   * Export canvas to TikZ
   */
  async export(
    canvas: FabricCanvas,
    options?: Omit<TikZExportOptions, 'format'>,
    onProgress?: ExportProgressCallback
  ): Promise<ExportResult> {
    const opts = { ...this.getDefaultOptions(), ...options };

    onProgress?.(0, 'Initializing TikZ export...');

    // Reset state
    this.colorIndex = 0;
    this.definedColors = new Map();

    // Validate options
    const validation = this.validateOptions({ ...opts, format: 'tikz' });
    if (!validation.valid) {
      throw new Error(`Invalid export options: ${validation.errors.join(', ')}`);
    }

    const lines: string[] = [];
    const unit = opts.unit || 'cm';
    const scale = opts.scale || 1;
    const unitFactor = UNIT_FACTORS[unit] * scale;
    const canvasHeight = canvas.getHeight();

    onProgress?.(10, 'Generating document structure...');

    // Generate preamble if standalone
    if (opts.standalone) {
      lines.push('\\documentclass[tikz,border=10pt]{standalone}');
      if (opts.includePreamble) {
        lines.push(...TIKZ_PACKAGES);
      }
      lines.push('');
    }

    // Add comment header
    if (opts.includeComments) {
      lines.push('% Generated by FINNISH - Scientific Illustration Tool');
      lines.push(`% Date: ${new Date().toISOString()}`);
      lines.push(`% Canvas size: ${canvas.getWidth()}x${canvas.getHeight()} pixels`);
      lines.push('');
    }

    // Collect all colors used
    onProgress?.(20, 'Analyzing colors...');
    const objects = canvas.getObjects();
    this.collectColors(objects);

    // Add color definitions
    if (this.definedColors.size > 0) {
      if (opts.includeComments) {
        lines.push('% Color definitions');
      }
      this.definedColors.forEach((name, color) => {
        lines.push(this.generateColorDefinition(color, name));
      });
      lines.push('');
    }

    // Begin document if standalone
    if (opts.standalone) {
      lines.push('\\begin{document}');
      lines.push('');
    }

    // Begin tikzpicture
    lines.push('\\begin{tikzpicture}');

    // Add background if set
    const bgColor = canvas.backgroundColor;
    if (bgColor && bgColor !== 'transparent' && typeof bgColor === 'string') {
      const colorName = this.getColorName(bgColor);
      const width = canvas.getWidth() * unitFactor;
      const height = canvas.getHeight() * unitFactor;
      lines.push(`  \\fill[${colorName}] (0,0) rectangle (${this.formatNumber(width)}${unit},${this.formatNumber(height)}${unit});`);
    }

    onProgress?.(30, 'Converting objects to TikZ...');

    // Convert each object to TikZ
    const totalObjects = objects.length;
    for (let i = 0; i < objects.length; i++) {
      const obj = objects[i];
      const progress = 30 + (i / totalObjects) * 60;
      onProgress?.(progress, `Converting object ${i + 1} of ${totalObjects}...`);

      const tikzCode = this.objectToTikZ(obj, unitFactor, unit, canvasHeight, opts.includeComments);
      if (tikzCode) {
        lines.push(tikzCode);
      }
    }

    // End tikzpicture
    lines.push('\\end{tikzpicture}');

    // End document if standalone
    if (opts.standalone) {
      lines.push('');
      lines.push('\\end{document}');
    }

    onProgress?.(95, 'Creating output file...');

    // Join lines and create blob
    const content = lines.join('\n');
    const blob = new Blob([content], { type: MIME_TYPES.tikz });
    const filename = `${opts.filename || 'illustration'}${FILE_EXTENSIONS.tikz}`;

    onProgress?.(100, 'Export complete');

    return {
      blob,
      filename,
      mimeType: MIME_TYPES.tikz,
      size: blob.size,
    };
  }

  /**
   * Collect all colors from objects and create named color definitions
   */
  private collectColors(objects: FabricObject[]): void {
    objects.forEach((obj) => {
      if (obj.fill && typeof obj.fill === 'string' && obj.fill !== 'transparent') {
        this.getColorName(obj.fill);
      }
      if (obj.stroke && typeof obj.stroke === 'string' && obj.stroke !== 'transparent') {
        this.getColorName(obj.stroke);
      }

      // Handle groups recursively
      if (obj.type === 'group') {
        const groupObj = obj as FabricObject & { _objects?: FabricObject[] };
        if (groupObj._objects) {
          this.collectColors(groupObj._objects);
        }
      }
    });
  }

  /**
   * Get or create a color name for a color value
   */
  private getColorName(color: string): string {
    if (this.definedColors.has(color)) {
      return this.definedColors.get(color)!;
    }

    // Check for common colors
    const commonColors: Record<string, string> = {
      '#000000': 'black',
      '#ffffff': 'white',
      '#ff0000': 'red',
      '#00ff00': 'green',
      '#0000ff': 'blue',
      '#ffff00': 'yellow',
      '#00ffff': 'cyan',
      '#ff00ff': 'magenta',
      '#808080': 'gray',
      black: 'black',
      white: 'white',
      red: 'red',
      green: 'green',
      blue: 'blue',
      yellow: 'yellow',
      cyan: 'cyan',
      magenta: 'magenta',
      gray: 'gray',
      grey: 'gray',
    };

    const normalized = color.toLowerCase();
    if (commonColors[normalized]) {
      return commonColors[normalized];
    }

    // Create a new color name
    const name = `color${this.colorIndex++}`;
    this.definedColors.set(color, name);
    return name;
  }

  /**
   * Generate a TikZ color definition
   */
  private generateColorDefinition(color: string, name: string): string {
    // Parse color to RGB
    const rgb = this.parseColorToRGB(color);
    if (!rgb) {
      return `\\definecolor{${name}}{rgb}{0,0,0}`;
    }

    return `\\definecolor{${name}}{RGB}{${rgb.r},${rgb.g},${rgb.b}}`;
  }

  /**
   * Parse a color string to RGB values
   */
  private parseColorToRGB(color: string): { r: number; g: number; b: number } | null {
    // Handle hex colors
    if (color.startsWith('#')) {
      const hex = color.slice(1);
      if (hex.length === 3) {
        return {
          r: parseInt(hex[0] + hex[0], 16),
          g: parseInt(hex[1] + hex[1], 16),
          b: parseInt(hex[2] + hex[2], 16),
        };
      } else if (hex.length === 6) {
        return {
          r: parseInt(hex.slice(0, 2), 16),
          g: parseInt(hex.slice(2, 4), 16),
          b: parseInt(hex.slice(4, 6), 16),
        };
      }
    }

    // Handle rgb/rgba
    const rgbMatch = color.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)/);
    if (rgbMatch) {
      return {
        r: parseInt(rgbMatch[1]),
        g: parseInt(rgbMatch[2]),
        b: parseInt(rgbMatch[3]),
      };
    }

    return null;
  }

  /**
   * Convert a Fabric.js object to TikZ code
   */
  private objectToTikZ(
    obj: FabricObject,
    unitFactor: number,
    unit: string,
    canvasHeight: number,
    includeComments?: boolean
  ): string | null {
    const lines: string[] = [];

    // Get common properties
    const left = obj.left || 0;
    const top = obj.top || 0;
    const scaleX = obj.scaleX || 1;
    const scaleY = obj.scaleY || 1;
    const angle = obj.angle || 0;

    // Transform coordinates (flip Y axis)
    const x = left * unitFactor;
    const y = (canvasHeight - top) * unitFactor;

    // Build style options
    const styleOptions = this.buildStyleOptions(obj);

    // Add comment if enabled
    if (includeComments) {
      lines.push(`  % ${obj.type} object`);
    }

    switch (obj.type) {
      case 'rect': {
        const rectObj = obj as FabricObject & { width: number; height: number; rx?: number; ry?: number };
        const width = (rectObj.width || 0) * scaleX * unitFactor;
        const height = (rectObj.height || 0) * scaleY * unitFactor;
        const cornerRadius = rectObj.rx ? rectObj.rx * unitFactor : 0;

        const x1 = this.formatNumber(x);
        const y1 = this.formatNumber(y - height);
        const x2 = this.formatNumber(x + width);
        const y2 = this.formatNumber(y);

        let cmd = `  \\draw[${styleOptions}]`;
        if (cornerRadius > 0) {
          cmd += ` [rounded corners=${this.formatNumber(cornerRadius)}${unit}]`;
        }
        cmd += ` (${x1}${unit},${y1}${unit}) rectangle (${x2}${unit},${y2}${unit});`;

        if (angle !== 0) {
          // Wrap in rotation scope
          const centerX = this.formatNumber(x + width / 2);
          const centerY = this.formatNumber(y - height / 2);
          lines.push(`  \\begin{scope}[rotate around={${this.formatNumber(-angle)}:(${centerX}${unit},${centerY}${unit})}]`);
          lines.push(`  ${cmd}`);
          lines.push(`  \\end{scope}`);
        } else {
          lines.push(cmd);
        }
        break;
      }

      case 'circle': {
        const circleObj = obj as FabricObject & { radius: number };
        const radius = (circleObj.radius || 0) * Math.max(scaleX, scaleY) * unitFactor;

        lines.push(
          `  \\draw[${styleOptions}] (${this.formatNumber(x)}${unit},${this.formatNumber(y)}${unit}) circle (${this.formatNumber(radius)}${unit});`
        );
        break;
      }

      case 'ellipse': {
        const ellipseObj = obj as FabricObject & { rx: number; ry: number };
        const rx = (ellipseObj.rx || 0) * scaleX * unitFactor;
        const ry = (ellipseObj.ry || 0) * scaleY * unitFactor;

        let cmd = `  \\draw[${styleOptions}] (${this.formatNumber(x)}${unit},${this.formatNumber(y)}${unit}) ellipse (${this.formatNumber(rx)}${unit} and ${this.formatNumber(ry)}${unit});`;

        if (angle !== 0) {
          lines.push(`  \\begin{scope}[rotate around={${this.formatNumber(-angle)}:(${this.formatNumber(x)}${unit},${this.formatNumber(y)}${unit})}]`);
          lines.push(`  ${cmd}`);
          lines.push(`  \\end{scope}`);
        } else {
          lines.push(cmd);
        }
        break;
      }

      case 'line': {
        const lineObj = obj as FabricObject & { x1: number; y1: number; x2: number; y2: number };
        const x1 = (left + (lineObj.x1 || 0) * scaleX) * unitFactor;
        const y1 = (canvasHeight - (top + (lineObj.y1 || 0) * scaleY)) * unitFactor;
        const x2 = (left + (lineObj.x2 || 0) * scaleX) * unitFactor;
        const y2 = (canvasHeight - (top + (lineObj.y2 || 0) * scaleY)) * unitFactor;

        lines.push(
          `  \\draw[${styleOptions}] (${this.formatNumber(x1)}${unit},${this.formatNumber(y1)}${unit}) -- (${this.formatNumber(x2)}${unit},${this.formatNumber(y2)}${unit});`
        );
        break;
      }

      case 'polyline':
      case 'polygon': {
        const polyObj = obj as FabricObject & { points: Array<{ x: number; y: number }> };
        if (!polyObj.points || polyObj.points.length < 2) break;

        const points = polyObj.points.map((p) => {
          const px = (left + p.x * scaleX) * unitFactor;
          const py = (canvasHeight - (top + p.y * scaleY)) * unitFactor;
          return `(${this.formatNumber(px)}${unit},${this.formatNumber(py)}${unit})`;
        });

        const operator = obj.type === 'polygon' ? ' -- cycle' : '';
        lines.push(`  \\draw[${styleOptions}] ${points.join(' -- ')}${operator};`);
        break;
      }

      case 'path': {
        const pathObj = obj as FabricObject & { path: Array<Array<string | number>> };
        if (!pathObj.path) break;

        const tikzPath = this.convertPathToTikZ(pathObj.path, left, top, scaleX, scaleY, unitFactor, unit, canvasHeight);
        if (tikzPath) {
          if (angle !== 0) {
            lines.push(`  \\begin{scope}[rotate around={${this.formatNumber(-angle)}:(${this.formatNumber(x)}${unit},${this.formatNumber(y)}${unit})}]`);
            lines.push(`  \\draw[${styleOptions}] ${tikzPath};`);
            lines.push(`  \\end{scope}`);
          } else {
            lines.push(`  \\draw[${styleOptions}] ${tikzPath};`);
          }
        }
        break;
      }

      case 'text':
      case 'i-text':
      case 'textbox': {
        const textObj = obj as FabricObject & {
          text: string;
          fontSize: number;
          fontFamily: string;
          fontWeight: string;
          fontStyle: string;
        };

        if (!textObj.text) break;

        const escapedText = this.escapeLatex(textObj.text);
        const fontSize = (textObj.fontSize || 12) * scaleY;
        const fillColor = textObj.fill && typeof textObj.fill === 'string' ? this.getColorName(textObj.fill) : 'black';

        // Build text style
        const textStyle: string[] = [];
        textStyle.push(`text=${fillColor}`);
        textStyle.push(`font=\\fontsize{${Math.round(fontSize)}pt}{${Math.round(fontSize * 1.2)}pt}\\selectfont`);

        if (textObj.fontWeight === 'bold' || (typeof textObj.fontWeight === 'number' && textObj.fontWeight >= 700)) {
          textStyle.push('font+=\\bfseries');
        }
        if (textObj.fontStyle === 'italic') {
          textStyle.push('font+=\\itshape');
        }

        let cmd = `  \\node[${textStyle.join(', ')}, anchor=north west]`;
        if (angle !== 0) {
          cmd += ` [rotate=${this.formatNumber(-angle)}]`;
        }
        cmd += ` at (${this.formatNumber(x)}${unit},${this.formatNumber(y)}${unit}) {${escapedText}};`;

        lines.push(cmd);
        break;
      }

      case 'group': {
        const groupObj = obj as FabricObject & { _objects?: FabricObject[] };
        if (groupObj._objects) {
          if (includeComments) {
            lines.push('  % Begin group');
          }
          lines.push(`  \\begin{scope}[shift={(${this.formatNumber(x)}${unit},${this.formatNumber(y)}${unit})}${angle !== 0 ? `, rotate=${this.formatNumber(-angle)}` : ''}]`);

          groupObj._objects.forEach((child) => {
            const childCode = this.objectToTikZ(child, unitFactor, unit, canvasHeight, includeComments);
            if (childCode) {
              lines.push(childCode);
            }
          });

          lines.push('  \\end{scope}');
          if (includeComments) {
            lines.push('  % End group');
          }
        }
        break;
      }

      case 'image':
        if (includeComments) {
          lines.push('  % Image objects are not supported in TikZ export');
        }
        break;

      default:
        if (includeComments) {
          lines.push(`  % Unsupported object type: ${obj.type}`);
        }
        break;
    }

    return lines.length > 0 ? lines.join('\n') : null;
  }

  /**
   * Build TikZ style options string from object properties
   */
  private buildStyleOptions(obj: FabricObject): string {
    const options: string[] = [];

    // Fill
    if (obj.fill && typeof obj.fill === 'string' && obj.fill !== 'transparent') {
      const fillColor = this.getColorName(obj.fill);
      options.push(`fill=${fillColor}`);

      // Fill opacity
      const fillOpacity = (obj as FabricObject & { fillOpacity?: number }).fillOpacity;
      if (fillOpacity !== undefined && fillOpacity < 1) {
        options.push(`fill opacity=${this.formatNumber(fillOpacity)}`);
      }
    }

    // Stroke
    if (obj.stroke && typeof obj.stroke === 'string' && obj.stroke !== 'transparent') {
      const strokeColor = this.getColorName(obj.stroke);
      options.push(`draw=${strokeColor}`);

      // Stroke width
      if (obj.strokeWidth && obj.strokeWidth > 0) {
        options.push(`line width=${this.formatNumber(obj.strokeWidth)}pt`);
      }

      // Stroke opacity
      const strokeOpacity = (obj as FabricObject & { strokeOpacity?: number }).strokeOpacity;
      if (strokeOpacity !== undefined && strokeOpacity < 1) {
        options.push(`draw opacity=${this.formatNumber(strokeOpacity)}`);
      }

      // Dash pattern
      if (obj.strokeDashArray && obj.strokeDashArray.length > 0) {
        const dashPattern = obj.strokeDashArray.map((d) => `${d}pt`).join(' ');
        options.push(`dash pattern=on ${dashPattern}`);
      }
    } else if (!obj.fill || obj.fill === 'transparent') {
      // If no fill and no stroke, default to draw
      options.push('draw');
    }

    // Global opacity
    if (obj.opacity !== undefined && obj.opacity < 1) {
      options.push(`opacity=${this.formatNumber(obj.opacity)}`);
    }

    return options.join(', ');
  }

  /**
   * Convert SVG path data to TikZ path
   */
  private convertPathToTikZ(
    path: Array<Array<string | number>>,
    offsetX: number,
    offsetY: number,
    scaleX: number,
    scaleY: number,
    unitFactor: number,
    unit: string,
    canvasHeight: number
  ): string | null {
    const commands: string[] = [];
    let currentX = 0;
    let currentY = 0;

    const transformX = (x: number) => this.formatNumber((offsetX + x * scaleX) * unitFactor);
    const transformY = (y: number) => this.formatNumber((canvasHeight - (offsetY + y * scaleY)) * unitFactor);

    for (const segment of path) {
      const cmd = segment[0] as string;

      switch (cmd.toUpperCase()) {
        case 'M': // Move to
          currentX = segment[1] as number;
          currentY = segment[2] as number;
          commands.push(`(${transformX(currentX)}${unit},${transformY(currentY)}${unit})`);
          break;

        case 'L': // Line to
          currentX = segment[1] as number;
          currentY = segment[2] as number;
          commands.push(`-- (${transformX(currentX)}${unit},${transformY(currentY)}${unit})`);
          break;

        case 'H': // Horizontal line to
          currentX = segment[1] as number;
          commands.push(`-- (${transformX(currentX)}${unit},${transformY(currentY)}${unit})`);
          break;

        case 'V': // Vertical line to
          currentY = segment[1] as number;
          commands.push(`-- (${transformX(currentX)}${unit},${transformY(currentY)}${unit})`);
          break;

        case 'C': // Cubic bezier
          {
            const x1 = segment[1] as number;
            const y1 = segment[2] as number;
            const x2 = segment[3] as number;
            const y2 = segment[4] as number;
            currentX = segment[5] as number;
            currentY = segment[6] as number;
            commands.push(
              `.. controls (${transformX(x1)}${unit},${transformY(y1)}${unit}) and (${transformX(x2)}${unit},${transformY(y2)}${unit}) .. (${transformX(currentX)}${unit},${transformY(currentY)}${unit})`
            );
          }
          break;

        case 'Q': // Quadratic bezier - convert to cubic
          {
            const qx1 = segment[1] as number;
            const qy1 = segment[2] as number;
            const qx2 = segment[3] as number;
            const qy2 = segment[4] as number;

            // Convert quadratic to cubic control points
            const cx1 = currentX + (2 / 3) * (qx1 - currentX);
            const cy1 = currentY + (2 / 3) * (qy1 - currentY);
            const cx2 = qx2 + (2 / 3) * (qx1 - qx2);
            const cy2 = qy2 + (2 / 3) * (qy1 - qy2);

            currentX = qx2;
            currentY = qy2;

            commands.push(
              `.. controls (${transformX(cx1)}${unit},${transformY(cy1)}${unit}) and (${transformX(cx2)}${unit},${transformY(cy2)}${unit}) .. (${transformX(currentX)}${unit},${transformY(currentY)}${unit})`
            );
          }
          break;

        case 'Z': // Close path
          commands.push('-- cycle');
          break;

        default:
          // Skip unsupported commands
          break;
      }
    }

    return commands.length > 0 ? commands.join(' ') : null;
  }

  /**
   * Escape special LaTeX characters in text
   */
  private escapeLatex(text: string): string {
    return text
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/\{/g, '\\{')
      .replace(/\}/g, '\\}')
      .replace(/\$/g, '\\$')
      .replace(/#/g, '\\#')
      .replace(/%/g, '\\%')
      .replace(/&/g, '\\&')
      .replace(/_/g, '\\_')
      .replace(/\^/g, '\\textasciicircum{}')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/</g, '\\textless{}')
      .replace(/>/g, '\\textgreater{}')
      .replace(/\|/g, '\\textbar{}');
  }

  /**
   * Format number for TikZ output (limit decimal places)
   */
  private formatNumber(num: number): string {
    // Round to 3 decimal places and remove trailing zeros
    return parseFloat(num.toFixed(3)).toString();
  }

  /**
   * Export as string (without blob)
   */
  async exportAsString(
    canvas: FabricCanvas,
    options?: Omit<TikZExportOptions, 'format'>
  ): Promise<string> {
    const result = await this.export(canvas, options);
    return await result.blob.text();
  }
}

export default TikZExporter;
