#!/usr/bin/env tsx
/**
 * Scan the healthicons-react package for ALL available icons
 * and generate a complete metadata file.
 *
 * USAGE: npx tsx scripts/ingest-icons/ingest-health-icons.ts
 *
 * OUTPUT: src/lib/illustration/data/icons-external/health-icons-full.ts
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';

const PACKAGE_DIR = path.join(process.cwd(), 'node_modules', 'healthicons-react', 'dist', 'esm', 'filled');
const OUTPUT = path.join(process.cwd(), 'src/lib/illustration/data/icons-external', 'health-icons-full.ts');

interface HealthIconEntry {
  componentName: string;
  displayName: string;
  category: string;
  keywords: string[];
}

// Map camelCase component names to readable names
function componentToDisplayName(name: string): string {
  return name
    .replace(/([A-Z])/g, ' $1')
    .replace(/^\s/, '')
    .replace(/\d+/g, ' ')
    .trim();
}

// Infer category from name patterns
function inferCategory(name: string): string {
  const n = name.toLowerCase();
  if (/heart|cardio|blood|vessel|artery|vein/.test(n)) return 'cardiovascular';
  if (/lung|breath|respiratory/.test(n)) return 'respiratory';
  if (/brain|neuro|nerve/.test(n)) return 'neurology';
  if (/bone|joint|spine|ortho/.test(n)) return 'orthopedics';
  if (/eye|vision|optic/.test(n)) return 'ophthalmology';
  if (/syringe|needle|vaccine|pill|medicine|drug/.test(n)) return 'pharmacy';
  if (/hospital|clinic|bed|ambulance|emergency/.test(n)) return 'facilities';
  if (/microscope|lab|test|tube|beaker/.test(n)) return 'laboratory';
  if (/baby|child|pediatric|pregnant/.test(n)) return 'pediatrics';
  if (/virus|bacteria|infection|mask/.test(n)) return 'infectious-disease';
  if (/tooth|dental/.test(n)) return 'dentistry';
  if (/surgery|scalpel|operation/.test(n)) return 'surgery';
  return 'general-medical';
}

async function main() {
  await mkdir(path.dirname(OUTPUT), { recursive: true });

  let files: string[];
  try {
    files = (await readdir(PACKAGE_DIR)).filter(f => f.endsWith('.js'));
  } catch {
    console.log('healthicons-react not found at expected path.');
    console.log('Trying alternative: scanning package exports...');
    // Alternative: read package.json exports
    const pkgJson = JSON.parse(
      await readFile(path.join(process.cwd(), 'node_modules', 'healthicons-react', 'package.json'), 'utf-8')
    );
    files = Object.keys(pkgJson.exports || {})
      .filter(k => k.includes('filled'))
      .map(k => path.basename(k));
  }

  const entries: HealthIconEntry[] = [];

  for (const file of files) {
    const name = file.replace(/\.(js|tsx?)$/, '');
    if (name === 'index') continue;

    entries.push({
      componentName: name,
      displayName: componentToDisplayName(name),
      category: inferCategory(name),
      keywords: componentToDisplayName(name).toLowerCase().split(/\s+/).filter(w => w.length > 2),
    });
  }

  const tsContent = `/**
 * Health Icons — Full Library Index
 * Auto-generated by scripts/ingest-icons/ingest-health-icons.ts
 * Source: healthicons-react (CC0)
 *
 * Total: ${entries.length} icons
 */

export interface HealthIconFullEntry {
  componentName: string;
  displayName: string;
  category: string;
  keywords: string[];
}

export const healthIconsFull: HealthIconFullEntry[] = ${JSON.stringify(entries, null, 2)};

export function searchHealthIconsFull(query: string): HealthIconFullEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return healthIconsFull.slice(0, 50);

  return healthIconsFull
    .filter(icon =>
      icon.displayName.toLowerCase().includes(q) ||
      icon.keywords.some(k => k.includes(q)) ||
      icon.category.includes(q)
    )
    .slice(0, 50);
}
`;

  await writeFile(OUTPUT, tsContent);
  console.log(`Generated ${entries.length} Health Icons entries → ${OUTPUT}`);
}

main().catch(console.error);
