#!/usr/bin/env tsx
/**
 * Ingest NIH BioArt Source icons
 *
 * USAGE:
 * 1. Download the BioArt SVG archive from https://bioart.niaid.nih.gov/
 *    (or manually save SVGs to ./raw-icons/nih-bioart/)
 * 2. Run: npx tsx scripts/ingest-icons/ingest-nih-bioart.ts
 *
 * OUTPUT:
 * - src/lib/illustration/data/icons-external/nih-bioart.ts
 * - Individual SVGs in .data/icons/nih-bioart/ (for R2 upload)
 */

import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const INPUT_DIR = path.join(process.cwd(), 'raw-icons', 'nih-bioart');
const OUTPUT_DATA = path.join(process.cwd(), 'src/lib/illustration/data/icons-external/nih-bioart.ts');
const OUTPUT_SVG_DIR = path.join(process.cwd(), '.data', 'icons', 'nih-bioart');

interface ProcessedIcon {
  id: string;
  name: string;
  category: string;
  keywords: string[];
  file: string;         // filename for external loading
  inlineSvg?: string;   // if SVG is small (<4KB), inline it
  license: string;
  source: string;
}

// NIH BioArt category mapping from folder names
const CATEGORY_MAP: Record<string, string> = {
  'anatomy': 'anatomy',
  'cells': 'cell-biology',
  'equipment': 'lab-equipment',
  'microbes': 'microbiology',
  'molecules': 'molecular-biology',
  'organs': 'anatomy',
  'proteins': 'molecular-biology',
  'tissues': 'histology',
  'viruses': 'virology',
  'bacteria': 'microbiology',
  'dna': 'genetics',
  'lab': 'lab-equipment',
};

async function normalizeSvg(svgContent: string): Promise<string> {
  // 1. Remove XML declaration
  let svg = svgContent.replace(/<\?xml[^?]*\?>/g, '');

  // 2. Remove comments
  svg = svg.replace(/<!--[\s\S]*?-->/g, '');

  // 3. Ensure viewBox exists
  if (!svg.includes('viewBox')) {
    const widthMatch = svg.match(/width="([^"]+)"/);
    const heightMatch = svg.match(/height="([^"]+)"/);
    if (widthMatch && heightMatch) {
      const w = parseFloat(widthMatch[1]);
      const h = parseFloat(heightMatch[1]);
      svg = svg.replace('<svg', `<svg viewBox="0 0 ${w} ${h}"`);
    }
  }

  // 4. Remove fixed width/height (let viewBox handle sizing)
  svg = svg.replace(/\s+width="[^"]*"/g, '');
  svg = svg.replace(/\s+height="[^"]*"/g, '');

  // 5. Remove empty groups
  svg = svg.replace(/<g>\s*<\/g>/g, '');

  return svg.trim();
}

function generateKeywords(name: string, category: string): string[] {
  const words = name.toLowerCase()
    .replace(/[-_]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2);

  const categoryWords = category.split('-');
  return [...new Set([...words, ...categoryWords])];
}

function sanitizeId(filename: string): string {
  return 'nih-' + filename
    .replace(/\.svg$/i, '')
    .replace(/[^a-zA-Z0-9]/g, '-')
    .toLowerCase();
}

async function main() {
  if (!existsSync(INPUT_DIR)) {
    console.log(`\nNo input directory found at: ${INPUT_DIR}`);
    console.log('To use this script:');
    console.log('1. Create: mkdir -p raw-icons/nih-bioart');
    console.log('2. Download NIH BioArt SVGs into that directory');
    console.log('3. Re-run this script');
    process.exit(0);
  }

  await mkdir(path.dirname(OUTPUT_DATA), { recursive: true });
  await mkdir(OUTPUT_SVG_DIR, { recursive: true });

  const files = await readdir(INPUT_DIR, { recursive: true });
  const svgFiles = files.filter(f => String(f).endsWith('.svg'));

  console.log(`Found ${svgFiles.length} SVG files`);

  const icons: ProcessedIcon[] = [];

  for (const file of svgFiles) {
    const filePath = path.join(INPUT_DIR, String(file));
    const content = await readFile(filePath, 'utf-8');
    const normalized = await normalizeSvg(content);
    const filename = path.basename(String(file));

    // Determine category from parent folder
    const relativePath = String(file).replace(path.sep, '/');
    const parentDir = relativePath.split(path.sep)[0] || relativePath.split('/')[0] || 'general';
    const category = CATEGORY_MAP[parentDir.toLowerCase()] || 'general';

    const name = filename
      .replace(/\.svg$/i, '')
      .replace(/[-_]/g, ' ')
      .replace(/\b\w/g, c => c.toUpperCase());

    const icon: ProcessedIcon = {
      id: sanitizeId(filename),
      name,
      category,
      keywords: generateKeywords(name, category),
      file: filename,
      license: 'Public Domain (NIH)',
      source: 'NIH BioArt Source',
    };

    // Inline small SVGs (<4KB), otherwise save externally
    if (normalized.length < 4096) {
      icon.inlineSvg = normalized;
    } else {
      await writeFile(path.join(OUTPUT_SVG_DIR, filename), normalized);
    }

    icons.push(icon);
  }

  // Generate TypeScript file
  const tsContent = `/**
 * NIH BioArt Source Icons
 * Auto-generated by scripts/ingest-icons/ingest-nih-bioart.ts
 * Source: https://bioart.niaid.nih.gov/
 * License: Public Domain
 *
 * Total: ${icons.length} icons
 */

export interface NIHBioArtIcon {
  id: string;
  name: string;
  category: string;
  keywords: string[];
  file: string;
  inlineSvg?: string;
  license: string;
  source: string;
}

export const nihBioArtIcons: NIHBioArtIcon[] = ${JSON.stringify(icons, null, 2)};

export function searchNIHBioArt(query: string): NIHBioArtIcon[] {
  const q = query.toLowerCase().trim();
  if (!q) return nihBioArtIcons;

  return nihBioArtIcons.filter(icon =>
    icon.name.toLowerCase().includes(q) ||
    icon.keywords.some(k => k.includes(q)) ||
    icon.category.includes(q)
  );
}
`;

  await writeFile(OUTPUT_DATA, tsContent);
  console.log(`Generated ${icons.length} NIH BioArt icon entries → ${OUTPUT_DATA}`);
}

main().catch(console.error);
