import { NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { ContentBlock } from "@/types/presentation";

interface SlideInput {
  title?: string;
  subtitle?: string;
  layout?: string;
  contentBlocks?: ContentBlock[];
  speakerNotes?: string;
}

interface ExportRequest {
  title: string;
  slides: SlideInput[];
}

export async function POST(req: Request) {
  try {
    const body: ExportRequest = await req.json();

    if (!body.slides?.length) {
      return NextResponse.json(
        { error: "At least one slide is required" },
        { status: 400 }
      );
    }

    const pdf = await PDFDocument.create();
    const font = await pdf.embedFont(StandardFonts.Helvetica);
    const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
    const fontItalic = await pdf.embedFont(StandardFonts.HelveticaOblique);

    const pageWidth = 612; // Letter width
    const pageHeight = 792; // Letter height
    const margin = 54; // 0.75 inch margins
    const contentWidth = pageWidth - 2 * margin;

    // Title page
    const titlePage = pdf.addPage([pageWidth, pageHeight]);
    titlePage.drawText(body.title || "Presentation", {
      x: margin,
      y: pageHeight - 200,
      size: 28,
      font: fontBold,
      color: rgb(0.12, 0.23, 0.37),
      maxWidth: contentWidth,
    });
    titlePage.drawText("Presentation Handout", {
      x: margin,
      y: pageHeight - 240,
      size: 14,
      font: fontItalic,
      color: rgb(0.5, 0.5, 0.5),
    });
    titlePage.drawText(`${body.slides.length} slides`, {
      x: margin,
      y: pageHeight - 265,
      size: 11,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    titlePage.drawText(`Generated by ScholarSync`, {
      x: margin,
      y: margin,
      size: 9,
      font,
      color: rgb(0.7, 0.7, 0.7),
    });

    // Content pages — 2 slides per page
    for (let i = 0; i < body.slides.length; i += 2) {
      const page = pdf.addPage([pageWidth, pageHeight]);
      const slidesOnPage = body.slides.slice(i, i + 2);

      for (let j = 0; j < slidesOnPage.length; j++) {
        const slide = slidesOnPage[j];
        const slideNum = i + j + 1;
        const yOffset = j === 0 ? pageHeight - margin : pageHeight / 2 - 10;

        // Slide number and title
        let y = yOffset;

        page.drawText(`Slide ${slideNum}`, {
          x: margin,
          y: y,
          size: 8,
          font,
          color: rgb(0.6, 0.6, 0.6),
        });
        y -= 16;

        if (slide.title) {
          const titleLines = wrapText(slide.title, fontBold, 16, contentWidth);
          for (const line of titleLines) {
            page.drawText(line, {
              x: margin,
              y,
              size: 16,
              font: fontBold,
              color: rgb(0.12, 0.23, 0.37),
            });
            y -= 20;
          }
        }
        y -= 4;

        // Content from blocks
        const blocks = slide.contentBlocks ?? [];
        for (const block of blocks) {
          if (y < (j === 0 ? pageHeight / 2 + 20 : margin + 40)) break;

          switch (block.type) {
            case "text":
              const textLines = wrapText(block.data.text, font, 10, contentWidth);
              for (const line of textLines) {
                if (y < (j === 0 ? pageHeight / 2 + 20 : margin + 40)) break;
                page.drawText(line, { x: margin, y, size: 10, font, color: rgb(0.2, 0.2, 0.2) });
                y -= 14;
              }
              y -= 4;
              break;

            case "bullets":
              for (const item of block.data.items) {
                if (y < (j === 0 ? pageHeight / 2 + 20 : margin + 40)) break;
                const bulletLines = wrapText(`\u2022 ${item}`, font, 10, contentWidth - 15);
                for (const line of bulletLines) {
                  page.drawText(line, { x: margin + 15, y, size: 10, font, color: rgb(0.2, 0.2, 0.2) });
                  y -= 13;
                }
              }
              y -= 4;
              break;

            case "quote":
              const quoteLines = wrapText(`"${block.data.text}"`, fontItalic, 10, contentWidth - 20);
              for (const line of quoteLines) {
                if (y < (j === 0 ? pageHeight / 2 + 20 : margin + 40)) break;
                page.drawText(line, { x: margin + 20, y, size: 10, font: fontItalic, color: rgb(0.3, 0.3, 0.3) });
                y -= 14;
              }
              if (block.data.attribution) {
                page.drawText(`— ${block.data.attribution}`, { x: margin + 20, y, size: 9, font, color: rgb(0.5, 0.5, 0.5) });
                y -= 14;
              }
              y -= 4;
              break;

            case "citation":
              const citLines = wrapText(`${block.data.text} (${block.data.source})`, font, 9, contentWidth - 15);
              for (const line of citLines) {
                if (y < (j === 0 ? pageHeight / 2 + 20 : margin + 40)) break;
                page.drawText(line, { x: margin + 10, y, size: 9, font, color: rgb(0.4, 0.4, 0.4) });
                y -= 12;
              }
              y -= 3;
              break;

            default:
              break;
          }
        }

        // Speaker notes
        if (slide.speakerNotes) {
          if (y > (j === 0 ? pageHeight / 2 + 40 : margin + 60)) {
            y -= 6;
            page.drawText("Speaker Notes:", {
              x: margin,
              y,
              size: 8,
              font: fontBold,
              color: rgb(0.5, 0.5, 0.5),
            });
            y -= 12;
            const noteLines = wrapText(slide.speakerNotes, font, 8, contentWidth);
            for (const line of noteLines.slice(0, 3)) {
              if (y < (j === 0 ? pageHeight / 2 + 20 : margin + 20)) break;
              page.drawText(line, { x: margin, y, size: 8, font, color: rgb(0.5, 0.5, 0.5) });
              y -= 11;
            }
          }
        }

        // Divider between slides on same page
        if (j === 0 && slidesOnPage.length > 1) {
          page.drawLine({
            start: { x: margin, y: pageHeight / 2 },
            end: { x: pageWidth - margin, y: pageHeight / 2 },
            thickness: 0.5,
            color: rgb(0.85, 0.85, 0.85),
          });
        }
      }

      // Page number
      page.drawText(`${Math.floor(i / 2) + 1}`, {
        x: pageWidth / 2,
        y: margin / 2,
        size: 9,
        font,
        color: rgb(0.7, 0.7, 0.7),
      });
    }

    const pdfBytes = await pdf.save();
    const safeTitle = (body.title || "presentation").replace(/[^a-zA-Z0-9]/g, "_");

    return new Response(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${safeTitle}_handout.pdf"`,
        "Content-Length": String(pdfBytes.byteLength),
      },
    });
  } catch (error) {
    console.error("PDF handout export error:", error);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}

function wrapText(
  text: string,
  font: any,
  fontSize: number,
  maxWidth: number
): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let currentLine = "";

  for (const word of words) {
    const testLine = currentLine ? `${currentLine} ${word}` : word;
    const testWidth = font.widthOfTextAtSize(testLine, fontSize);

    if (testWidth > maxWidth && currentLine) {
      lines.push(currentLine);
      currentLine = word;
    } else {
      currentLine = testLine;
    }
  }

  if (currentLine) lines.push(currentLine);
  return lines;
}
