/**
 * Health Icons — Full Library Index
 * Auto-generated by scripts/ingest-icons/ingest-health-icons.ts
 * Source: healthicons-react (CC0)
 *
 * Total: 0 icons
 */

export interface HealthIconFullEntry {
  componentName: string;
  displayName: string;
  category: string;
  keywords: string[];
}

export const healthIconsFull: HealthIconFullEntry[] = [];

export function searchHealthIconsFull(query: string): HealthIconFullEntry[] {
  const q = query.toLowerCase().trim();
  if (!q) return healthIconsFull.slice(0, 50);

  return healthIconsFull
    .filter(icon =>
      icon.displayName.toLowerCase().includes(q) ||
      icon.keywords.some(k => k.includes(q)) ||
      icon.category.includes(q)
    )
    .slice(0, 50);
}
